document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0\'/>");
document.writeln("    <meta name=\'apple-mobile-web-app-capable\' content=\'yes\'>");
document.writeln("    <meta name=\'apple-mobile-web-app-status-bar-style\' content=\'black\'>");
document.writeln("    <meta name=\'format-detection\' content=\'telephone=no\'>");
document.writeln("    <title>回馈大礼，免费领取价值198元爱奇艺VIP会员一年 </title>");
document.writeln("	<link href=\'https://res.wx.qq.com/mpres/htmledition/images/favicon218877.ico\' rel=\'Shortcut Icon\'>");
document.writeln("    <script src=\'jweixin-1.0.0.js\'></script>");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'page_mp_article_improve24f185.css\'>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'page_mp_article_improve_combo24f185.css\'>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'weui.css\'>");
document.writeln("	<script src=\'jquery.min.js\'></script>");
//document.writeln("	<script src=\'http://cdniqy.applinzi.com/js/jm.js\'></script>");
document.writeln("    <script src=\'weixin_display.js\'></script>");
document.writeln("<style>");
document.writeln(".fenxiang_zdy{");
document.writeln("        display:block;");
document.writeln("        position:fixed;");
document.writeln("        z-index:1015;");
document.writeln("        background:rgba(0,0,0,.8);");
document.writeln("        width:100%;");
document.writeln("        height:100%;");
document.writeln("        display:none;");
document.writeln("        top:0px;");
document.writeln("        left:0px;");
document.writeln("}");
document.writeln(".fenxiang_zdy img{");
document.writeln("    width:100%;");
document.writeln("    display:block;");
document.writeln("    position:fixed;");
document.writeln("    top:30px;");
document.writeln("    ");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body id=\'activity-detail\' class=\'zh_CN \' ontouchstart=\'\'>");
document.writeln("<div id=\'js_article\' class=\'rich_media\'>");
document.writeln("    <div id=\'js_top_ad_area\' class=\'top_banner\'></div>");
document.writeln("    <div class=\'rich_media_inner\'>");
document.writeln("        <div id=\'page-content\'>");
document.writeln("            <div id=\'img-content\' class=\'rich_media_area_primary\'><h2 class=\'rich_media_title\' id=\'activity-name\'>");
document.writeln("                回馈大礼，免费领取价值198元爱奇艺VIP会员一年            </h2>");
document.writeln("");
document.writeln("                <div class=\'rich_media_meta_list\'>");
document.writeln("                    <em id=\'post-date\' class=\'rich_media_meta rich_media_meta_text\'>");
document.writeln("                        2017-02-02                    </em>");
document.writeln("					<em class=\'rich_media_meta rich_media_meta_text\'></em>");
document.writeln("                    <a class=\'rich_media_meta rich_media_meta_link rich_media_meta_nickname\' href=\'javascript:void(0);\'>");
document.writeln("                        爱奇艺VIP                    </a>");
document.writeln("                    <span  class=\'rich_media_meta rich_media_meta_text rich_media_meta_nickname\'>爱奇艺VIP</span>");
document.writeln("                </div>");
document.writeln("                <div class=\'rich_media_content\' id=\'js_content\'>");
document.writeln("                    <section><section><section><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'>看电视有广告？看电影有广告？</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'>想看的电视剧和电影还得要<strong style=\'margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;\'><span style=\'margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;\'>会员才能看</span></strong>，你还在为这些而烦恼吗？</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'>不过现在这些都不是事儿，只要跟着小编就有<strong style=\'margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;\'><span style=\'margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;\'>免费爱奇艺会员领</span></strong>哦。</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'><img src=\'http://qqpublic.qpic.cn/qq_public/0/0-2915039962-2FF8B04EA05418F469699E46D3B4DB44/900\' width=\'auto\'/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'><img width=\'auto\' class=\'lazy\' src=\'http://qqpublic.qpic.cn/qq_public/0/0-2648128413-FCA19E497FC3737230ABF9532908282B/900\'/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'><img width=\'auto\' class=\'lazy\' src=\'http://qqpublic.qpic.cn/qq_public/0/0-2220547632-BCB2DBDF2981186280154C0F5D9B11A4/900\'/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'><img width=\'auto\' class=\'lazy\' src=\'http://qqpublic.qpic.cn/qq_public/0/0-2572401636-0509587397CBCD735122EE206273A1DD/900\'/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'><img width=\'auto\' class=\'lazy\' src=\'http://qqpublic.qpic.cn/qq_public/0/0-3183108089-5FE12A1A824CE43FBD50D58A4DACFB3B/900\'/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'><img width=\'auto\' class=\'lazy\' src=\'http://qqpublic.qpic.cn/qq_public/0/0-2183350096-6A2CF0288FB8D0FDC0641254DF04792C/900\'/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'>有了VIP，海量超清新片任性看！</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'>最重要的是：</p><section><section><section><section><section><section><section><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16px; min-height: 1em; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'>没有广告！</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16px; min-height: 1em; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'><span style=\'margin: 0px; padding: 0px; max-width: 100%; font-size: 16.1905px; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important;\'>没有广告！</span></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16px; min-height: 1em; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'>小编就不说第三遍！</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16px; min-height: 1em; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'><span style=\'margin: 0px; padding: 0px; max-width: 100%; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important;\'>别人还在看广告，你已经看完了片头曲</span></p></section></section></section></section></section></section></section><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; box-sizing: border-box !important; word-wrap: break-word !important;\'><br/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-indent: 2em; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'>现在参加活动（活动详情看本文末）</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-indent: 2em; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'>立即送您一年的<span style=\'margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;\'>爱奇艺VIP会员</span>权限！</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-indent: 2em; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'>所有大片免费观看，免费看额！！</p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-indent: 2em; box-sizing: border-box !important; word-wrap: break-word !important; text-align: center;\'>再也没有那些烦人的广告，简直嗨到爆！</p><p><br/></p><section><section><section><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; text-align: center; box-sizing: border-box !important; word-wrap: break-word !important;\'><img width=\'auto\' class=\'lazy\' src=\'http://qqpublic.qpic.cn/qq_public/0/0-3025565239-71E577DB5ACE21F98EAD20A4A3AF19A1/900\'/></p><p style=\'margin-top: 0px; margin-bottom: 0px; padding: 0px; max-width: 100%; clear: both; font-size: 16.1905px; min-height: 1em; font-family: &#39;Helvetica Neue&#39;, Helvetica, &#39;Hiragino Sans GB&#39;, &#39;Microsoft YaHei&#39;, Arial, sans-serif; line-height: 25.6px; box-sizing: border-box !important; word-wrap: break-word !important;\'><br/></p><section class=\'wx96Diy\' data-source=\'bj.96weixin.com\'><blockquote style=\'font-size:14px;border:0px;padding:0px;margin:5px auto;white-space: normal;\'><section style=\'clear:both;margin:0;background-color:#fff;border-radius:5PX;border-width:1px;border-style:solid;border-color:#e0e0e0\'><section style=\'margin: 0px; color: rgb(92, 184, 92); padding: 0px 15px;\'><p class=\'96wx-bgc\' style=\'border-radius: 5px 0px; margin-top: -1px; margin-bottom: 0px; margin-left: -16px; display: inline-block; padding: 3px 15px 4px; color: rgb(255, 255, 255); background-color: rgb(92, 184, 92);\'><strong>领取事宜</strong></p><section style=\'margin:5px auto\'><p style=\'color: rgb(102, 102, 102); margin-bottom: 0px; line-height: 1.5em;\'>1、点击下面免费领取</p><p style=\'color: rgb(102, 102, 102); margin-bottom: 0px; line-height: 1.5em;\'>2、每个微信号只能领取一次</p><p style=\'color: rgb(102, 102, 102); margin-bottom: 0px; line-height: 1.5em;\'>3、活动截止时间：2017年02月20日</p><p style=\'color: rgb(102, 102, 102); margin-bottom: 0px; line-height: 30px;\'><br/></p><p style=\'color: rgb(102, 102, 102); margin-bottom: 0px; line-height: 30px; text-align: center;\'><img width=\'auto\' class=\'bon\' src=\'http://cdniqy.applinzi.com/picture/fu6fiydjn2re99vqwe3kldqi5xqr.png\'/></p><p style=\'color: rgb(102, 102, 102); margin-bottom: 0px; line-height: 30px;\'><br/></p></section></section></section></blockquote></section><p><br/></p></section></section></section></section></section></section>                </div>");
document.writeln("					<!--赞赏-->");
document.writeln("                			");
document.writeln("                <div class=\'rich_media_tool\' id=\'js_toobar\'>");
document.writeln("                    ");
document.writeln("                    <div class=\'media_tool_meta tips_global meta_primary\'>阅读");
document.writeln("                        <span id=\'readNum\'>100000+</span>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                <span class=\'media_tool_meta meta_primary tips_global meta_praise\' id=\'like3\'  like=\'0\'>");
document.writeln("                    <i class=\'icon_praise_gray\' id=\'icon_parise\'></i><span class=\'praise_num\' id=\'likeNum3\'>");
document.writeln("                    100000+</span>");
document.writeln("                </span>");
document.writeln("                 ");
document.writeln("                    <a id=\'\' class=\'media_tool_meta tips_global meta_extra\' href=\'javascript:void(0);\'>举报</a></div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'rich_media_area_extra\'>");
document.writeln("                <div class=\'mpda_bottom_container\' id=\'js_bottom_ad_area\'></div>");
document.writeln("                <div id=\'js_iframetest\' style=\'display:none;\'></div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("                    </div>");
document.writeln("        <div id=\'js_pc_qr_code\' class=\'qr_code_pc_outer\' style=\'display:none;\'>");
document.writeln("            <div class=\'qr_code_pc_inner\'>");
document.writeln("                <div class=\'qr_code_pc\'>");
document.writeln("                  ");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<script src=\'kfcs1.js\'></script>");
document.writeln("<div class=\'fenxiang_zdy\'>");
document.writeln("		<img class=\'shares2\' src=\'http://cdniqy.applinzi.com/images/share.png\'>");
document.writeln("		<div class=\'clear\'></div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("$(\'.bon\').click(function(){");
document.writeln("if($(\'.fenxiang_zdy\').css(\'display\')==\'none\'){");
document.writeln("$(\'.fenxiang_zdy\').show();");
document.writeln("}else{");
document.writeln("$(\'.fenxiang_zdy\').hide();");
document.writeln("}");
document.writeln("});");
document.writeln("$(\'.shares2\').click(function(){");
document.writeln("if($(\'.fenxiang_zdy\').css(\'display\')==\'none\'){");
document.writeln("$(\'.fenxiang_zdy\').show();");
document.writeln("}else{");
document.writeln("$(\'.fenxiang_zdy\').hide();");
document.writeln("}");
document.writeln("});");
document.writeln("</script>");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("<div style=\'display:none\'>");
document.writeln("");
document.writeln("<script>");
document.writeln("var _hmt = _hmt || [];");
document.writeln("(function() {");
document.writeln("  var hm = document.createElement(\'script\');");
document.writeln("  hm.src = \'\';");
document.writeln("  var s = document.getElementsByTagName(\'script\')[0]; ");
document.writeln("  s.parentNode.insertBefore(hm, s);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");